apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sqs-dp
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      containers:
      - name: {{ .Values.appLabel }}
        image: {{ .Values.sqsProcessorDevImage.repository }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name}}
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: AWS_REGION
        - name: AWS_SQS_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: AWS_SQS_URL