kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: whizstream-local
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080   # expose NodePort 80 for ingress or ArgoCD
        hostPort: 8080
        protocol: TCP
      - containerPort: 30443
        hostPort: 8443
        protocol: TCP