apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sqs-processor
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/whizstream-aakash/whizstream-gitops.git
    targetRevision: HEAD
    path: helm/sqs-poller-chart
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
